name: Update production

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 0"

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}
      - name: Update Git branch production
        run: |
          git config user.name "Update branch"
          git config user.email github-actions@github.com
          git checkout production
          git rebase main
      - name: Push the updated branch production
        run: |
          git push origin production
